//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vdk.AutoCompleter.Wcf.ClientModule.AutoCompleteWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AutoCompleteWcfService.IAutoCompleteWcfService")]
    public interface IAutoCompleteWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoCompleteWcfService/Get", ReplyAction="http://tempuri.org/IAutoCompleteWcfService/GetResponse")]
        string[] Get(string prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoCompleteWcfService/Get", ReplyAction="http://tempuri.org/IAutoCompleteWcfService/GetResponse")]
        System.Threading.Tasks.Task<string[]> GetAsync(string prefix);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutoCompleteWcfServiceChannel : Vdk.AutoCompleter.Wcf.ClientModule.AutoCompleteWcfService.IAutoCompleteWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoCompleteWcfServiceClient : System.ServiceModel.ClientBase<Vdk.AutoCompleter.Wcf.ClientModule.AutoCompleteWcfService.IAutoCompleteWcfService>, Vdk.AutoCompleter.Wcf.ClientModule.AutoCompleteWcfService.IAutoCompleteWcfService {
        
        public AutoCompleteWcfServiceClient() {
        }
        
        public AutoCompleteWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoCompleteWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoCompleteWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoCompleteWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Get(string prefix) {
            return base.Channel.Get(prefix);
        }
        
        public System.Threading.Tasks.Task<string[]> GetAsync(string prefix) {
            return base.Channel.GetAsync(prefix);
        }
    }
}
